env:
  browser: true
  es6: true
  node: true
  jasmine: true
  jest: true
extends:
  - plugin:prettier/recommended
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules: {
    '@typescript-eslint/no-unused-vars': 2,
    arrow-body-style: 0,
    consistent-return: 0,
    function-paren-newline: 0,
    indent: 0,
    implicit-arrow-linebreak: 0,
    import/extensions: 0,
    import/first: 0,
    import/no-extraneous-dependencies: 0,
    import/no-unresolved: 0,
    import/prefer-default-export: 0,
    jsx-a11y/anchor-is-valid: 0,
    lines-between-class-members: 0,
    max-classes-per-file: 0,
    max-len: 0,
    newline-per-chained-call: 0,
    no-alert: 0,
    no-empty-function: 0,
    no-plusplus: 0,
    no-undef: 0,
    no-unused-vars: 0,
    no-useless-constructor: 0,
    object-curly-newline:
      [2, { consistent: true, minProperties: 10, multiline: true }],
    operator-linebreak: 0,
    prettier/prettier: 2,
    react/jsx-indent: 0,
    react/jsx-curly-brace-presence: 0,
    react/jsx-curly-newline: 0,
    react/jsx-fragments: 0,
    react/jsx-filename-extension: [2, { extensions: [.tsx] }],
    react/jsx-wrap-multilines: 0,
    react/jsx-one-expression-per-line: 0,
    react/jsx-props-no-spreading: 0,
    react/no-unescaped-entities: 0,

    # We use Typescript for validating props
    react/prop-types: 0,
    react/react-in-jsx-scope: 0,
    react-hooks/exhaustive-deps: 2,
    react-hooks/rules-of-hooks: 2,
    semi-style: 0,
  }
